export const mockTagList: Tag[] = [
  { name: "High protein", color: "#B42318" },
  { name: "In season", color: "#B54708" },
  { name: "Local", color: "#027A48" },
  { name: "Organic", color: "#6941C6" },
];

export const mockMenuList: Menu[] = [
  {
    id: 1,
    dish_name: "Risotto ai Funghi",
    description: "Creamy Arborio rice cooked in...",
    local_origin: "Mediterranean",
    rate: 4.3,
    price: 22.99,
    image: "/assets/menus/menu1.jpg",
    category: "",
    restaurant: {
      id: 1,
      name: "Bella Italia",
      description: "",
      image: "/assets/brands/brand1.jpg",
      geometry: {
        lat: 0,
        lng: 0,
      },
    },
  },
  {
    id: 2,
    dish_name: "Fettuccine Alfredo",
    description: "Velvety strands of fettuccine...",
    local_origin: "American",
    rate: 4.5,
    price: 19.99,
    image: "/assets/menus/menu2.jpg",
    category: "",
    restaurant: {
      id: 2,
      name: "Olive Garden",
      description: "",
      image: "/assets/brands/brand2.jpg",
      geometry: {
        lat: 0,
        lng: 0,
      },
    },
  },
  {
    id: 1,
    dish_name: "Risotto ai Funghi",
    description: "Creamy Arborio rice cooked in...",
    local_origin: "Mediterranean",
    rate: 4.3,
    price: 22.99,
    image: "/assets/menus/menu1.jpg",
    category: "",
    restaurant: {
      id: 1,
      name: "Bella Italia",
      description: "",
      image: "/assets/brands/brand1.jpg",
      geometry: {
        lat: 0,
        lng: 0,
      },
    },
    is_featured: true,
  },
  {
    id: 2,
    dish_name: "Fettuccine Alfredo",
    description: "Velvety strands of fettuccine...",
    local_origin: "American",
    rate: 4.5,
    price: 19.99,
    image: "/assets/menus/menu2.jpg",
    category: "",
    restaurant: {
      id: 2,
      name: "Olive Garden",
      description: "",
      image: "/assets/brands/brand2.jpg",
      geometry: {
        lat: 0,
        lng: 0,
      },
    },
  },
  {
    id: 1,
    dish_name: "Risotto ai Funghi",
    description: "Creamy Arborio rice cooked in...",
    local_origin: "Mediterranean",
    rate: 4.3,
    price: 22.99,
    image: "/assets/menus/menu1.jpg",
    category: "",
    restaurant: {
      id: 1,
      name: "Bella Italia",
      description: "",
      image: "/assets/brands/brand1.jpg",
      geometry: {
        lat: 0,
        lng: 0,
      },
    },
  },
  {
    id: 2,
    dish_name: "Fettuccine Alfredo",
    description: "Velvety strands of fettuccine...",
    local_origin: "American",
    rate: 4.5,
    price: 19.99,
    image: "/assets/menus/menu2.jpg",
    category: "",
    restaurant: {
      id: 2,
      name: "Olive Garden",
      description: "",
      image: "/assets/brands/brand2.jpg",
      geometry: {
        lat: 0,
        lng: 0,
      },
    },
  },
  {
    id: 1,
    dish_name: "Risotto ai Funghi",
    description: "Creamy Arborio rice cooked in...",
    local_origin: "Mediterranean",
    rate: 4.3,
    price: 22.99,
    image: "/assets/menus/menu1.jpg",
    category: "",
    restaurant: {
      id: 1,
      name: "Bella Italia",
      description: "",
      image: "/assets/brands/brand1.jpg",
      geometry: {
        lat: 0,
        lng: 0,
      },
    },
  },
  {
    id: 2,
    dish_name: "Fettuccine Alfredo",
    description: "Velvety strands of fettuccine...",
    local_origin: "American",
    rate: 4.5,
    price: 19.99,
    image: "/assets/menus/menu2.jpg",
    category: "",
    restaurant: {
      id: 2,
      name: "Olive Garden",
      description: "",
      image: "/assets/brands/brand2.jpg",
      geometry: {
        lat: 0,
        lng: 0,
      },
    },
  },
  {
    id: 1,
    dish_name: "Risotto ai Funghi",
    description: "Creamy Arborio rice cooked in...",
    local_origin: "Mediterranean",
    rate: 4.3,
    price: 22.99,
    image: "/assets/menus/menu1.jpg",
    category: "",
    restaurant: {
      id: 1,
      name: "Bella Italia",
      description: "",
      image: "/assets/brands/brand1.jpg",
      geometry: {
        lat: 0,
        lng: 0,
      },
    },
  },
  {
    id: 2,
    dish_name: "Fettuccine Alfredo",
    description: "Velvety strands of fettuccine...",
    local_origin: "American",
    rate: 4.5,
    price: 19.99,
    image: "/assets/menus/menu2.jpg",
    category: "",
    restaurant: {
      id: 2,
      name: "Olive Garden",
      description: "",
      image: "/assets/brands/brand2.jpg",
      geometry: {
        lat: 0,
        lng: 0,
      },
    },
  },
];

export const mockMenuList1: Menu[] = [
  {
    id: 1,
    dish_name: "Slow-Roasted Lamb Shoulder",
    description:
      "Tender lamb shoulder slow-roasted to perfection, infused with aromatic herbs and...",
    local_origin: "American",
    rate: 4.3,
    price: 22.99,
    image: "/assets/menus/menu1.jpg",
    category: "",
    restaurant: {
      id: 1,
      name: "Nobu",
      description: "",
      image: "/assets/brands/brand3.jpg",
      geometry: {
        lat: 0,
        lng: 0,
        address: "Midtown, New York",
      },
    },
    tags: mockTagList,
    like: true,
  },
  {
    id: 2,
    dish_name: "Mediterranean Lamb Shoulder Platter",
    description:
      "Succulent lamb shoulder marinated in Mediterranean spices, grilled to juicy perfect...",
    local_origin: "American",
    rate: 4.3,
    price: 22.99,
    image: "/assets/menus/menu2.jpg",
    category: "",
    restaurant: {
      id: 1,
      name: "Le Bernardin",
      description: "",
      image: "/assets/brands/brand4.jpg",
      geometry: {
        lat: 0,
        lng: 0,
        address: "Los Angeles, New York",
      },
    },
    tags: mockTagList,
  },
  {
    id: 1,
    dish_name: "Slow-Roasted Lamb Shoulder",
    description:
      "Tender lamb shoulder slow-roasted to perfection, infused with aromatic herbs and...",
    local_origin: "American",
    rate: 4.3,
    price: 22.99,
    image: "/assets/menus/menu1.jpg",
    category: "",
    restaurant: {
      id: 1,
      name: "Nobu",
      description: "",
      image: "/assets/brands/brand3.jpg",
      geometry: {
        lat: 0,
        lng: 0,
        address: "Midtown, New York",
      },
    },
    tags: mockTagList,
    like: true,
  },
  {
    id: 2,
    dish_name: "Mediterranean Lamb Shoulder Platter",
    description:
      "Succulent lamb shoulder marinated in Mediterranean spices, grilled to juicy perfect...",
    local_origin: "American",
    rate: 4.3,
    price: 22.99,
    image: "/assets/menus/menu2.jpg",
    category: "",
    restaurant: {
      id: 1,
      name: "Le Bernardin",
      description: "",
      image: "/assets/brands/brand4.jpg",
      geometry: {
        lat: 0,
        lng: 0,
        address: "Los Angeles, New York",
      },
    },
    tags: mockTagList,
  },
  {
    id: 1,
    dish_name: "Slow-Roasted Lamb Shoulder",
    description:
      "Tender lamb shoulder slow-roasted to perfection, infused with aromatic herbs and...",
    local_origin: "American",
    rate: 4.3,
    price: 22.99,
    image: "/assets/menus/menu1.jpg",
    category: "",
    restaurant: {
      id: 1,
      name: "Nobu",
      description: "",
      image: "/assets/brands/brand3.jpg",
      geometry: {
        lat: 0,
        lng: 0,
        address: "Midtown, New York",
      },
    },
    tags: mockTagList,
  },
];

export const mockIngredientList: Ingredient[] = [
  {
    name: "Buffalo mozzarella",
    description: "Creamy, tangy, elevates salads...",
    image: "/assets/ingredients/ingredient1.jpg",
  },
  {
    name: "Prosciutto",
    description: "Savory, thinly sliced, adds depth...",
    image: "/assets/ingredients/ingredient2.jpg",
  },
  {
    name: "Buffalo mozzarella",
    description: "Creamy, tangy, elevates salads...",
    image: "/assets/ingredients/ingredient1.jpg",
  },
  {
    name: "Prosciutto",
    description: "Savory, thinly sliced, adds depth...",
    image: "/assets/ingredients/ingredient2.jpg",
  },
  {
    name: "Buffalo mozzarella",
    description: "Creamy, tangy, elevates salads...",
    image: "/assets/ingredients/ingredient1.jpg",
  },
  {
    name: "Prosciutto",
    description: "Savory, thinly sliced, adds depth...",
    image: "/assets/ingredients/ingredient2.jpg",
  },
  {
    name: "Buffalo mozzarella",
    description: "Creamy, tangy, elevates salads...",
    image: "/assets/ingredients/ingredient1.jpg",
  },
  {
    name: "Prosciutto",
    description: "Savory, thinly sliced, adds depth...",
    image: "/assets/ingredients/ingredient2.jpg",
  },
  {
    name: "Buffalo mozzarella",
    description: "Creamy, tangy, elevates salads...",
    image: "/assets/ingredients/ingredient1.jpg",
  },
  {
    name: "Prosciutto",
    description: "Savory, thinly sliced, adds depth...",
    image: "/assets/ingredients/ingredient2.jpg",
  },
  {
    name: "Buffalo mozzarella",
    description: "Creamy, tangy, elevates salads...",
    image: "/assets/ingredients/ingredient1.jpg",
  },
  {
    name: "Prosciutto",
    description: "Savory, thinly sliced, adds depth...",
    image: "/assets/ingredients/ingredient2.jpg",
  },
];

export const mockCities = [
  "New York",
  "Chicago",
  "Melbourne",
  "Sydney",
  "London",
  "Paris",
  "Tokyo",
];

export const mockChartItemList: ChartItem[] = [
  {
    name: "Garlic Mesh",
    value: 144,
    image: "/assets/background/pair_food1.png",
  },
  { name: "Rosemary", value: 120, image: "/assets/background/pair_food2.png" },
  { name: "Mint", value: 101, image: "/assets/background/pair_food3.png" },
  {
    name: "Grilled Veggies",
    value: 94,
    image: "/assets/background/pair_food1.png",
  },
  {
    name: "Roast Roots",
    value: 55,
    image: "/assets/background/pair_food2.png",
  },
  {
    name: "Greek Salad",
    value: 42,
    image: "/assets/background/pair_food3.png",
  },
  {
    name: "Creamy Polenta",
    value: 32,
    image: "/assets/background/pair_food1.png",
  },
  { name: "Tabbouleh", value: 20, image: "/assets/background/pair_food2.png" },
  {
    name: "Braised Greens",
    value: 11,
    image: "/assets/background/pair_food3.png",
  },
  {
    name: "Ratatouille",
    value: 10,
    image: "/assets/background/pair_food2.png",
  },
];
